### ISSUE TITLE
Side parts of Dognut chart are squashed 

### ISSUE THREAD

**Issue by ByeongSooLee-KR** [toomuchdesign/react-minimal-pie-chart#219]
## What is the current behaviour?
side parts of dognut piechart are squashed . No matter how I changed Css by modifying width, putting padding, it doesn't work like below picture. 
![image](https://user-images.githubusercontent.com/61416556/114818829-657b6280-9df7-11eb-9e7b-777dfb902772.png)

```Jsx
                    <div className="wrapper" key={index}>
                        <PieChart
                            labelStyle={(idx) => ({
                                fill: rate.data[idx].color,
                            })}
                            animate
                            animationDuration={1000}
                            animationEasing="ease-out"
                            center={[50, 50]}
                            data={rate.data}
                            lengthAngle={360}
                            lineWidth={30}
                            paddingAngle={1}
                            radius={50}
                            startAngle={270}
                            style={{
                                position: 'relative',
                            }}
                            viewBoxSize={[100, 100]}
                            segmentsStyle={{ transition: 'stroke .8s', cursor: 'pointer' }}
                            segmentsShift={2}
                        />
                        {/* <Label>{rate.label}</Label>
                        <Text>{rate.text}</Text> */}
                    </div>
```

```Css
export const DetailSoolRatesWrapper = styled(Wrapper)`
    font-size: 14px;
    font-weight: bold;
    margin-top: 40px;
    margin-bottom: 228px;
    padding: 0 80px;
    .container {
        display: flex;
        justify-content: space-between;
    }
    .wrapper {
        width: 80px;
        position: relative;
        align-items: center;
    }
    .right-text {
        color: ${blue};
        font-size: 11px;
        font-weight: normal;
        margin-top: 40px;
        text-align: right;
    }
    @media (max-width: 768px) {
    }
`;
```

...

## What is the expected behaviour?
I want it not to be squashed . please let me know 
Thanks in advance 
...
